'use client';
import { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useToast } from '../context/ToastContext';

/**
 * QuickReplyModal — A fast, non-intrusive way to reply to chat messages straight from a notification.
 * Listens to "open-quick-reply" custom event.
 */
export default function QuickReplyModal() {
    const [isOpen, setIsOpen] = useState(false);
    const [replyInfo, setReplyInfo] = useState(null);
    const [message, setMessage] = useState('');
    const [isSending, setIsSending] = useState(false);
    const inputRef = useRef(null);
    const { promiseToast } = useToast();

    // Listen for the custom event generated by the "Responder" button on Sileo toasts
    useEffect(() => {
        const handleOpen = (e) => {
            setReplyInfo(e.detail);
            setIsOpen(true);
            setMessage('');
            setTimeout(() => inputRef.current?.focus(), 100);
        };
        window.addEventListener('open-quick-reply', handleOpen);
        return () => window.removeEventListener('open-quick-reply', handleOpen);
    }, []);

    // Close on escape
    useEffect(() => {
        const handleKey = (e) => {
            if (e.key === 'Escape') setIsOpen(false);
        };
        window.addEventListener('keydown', handleKey);
        return () => window.removeEventListener('keydown', handleKey);
    }, []);

    const handleSend = async (e) => {
        e.preventDefault();
        if (!message.trim() || !replyInfo) return;

        setIsSending(true);

        const sendPromise = new Promise(async (resolve, reject) => {
            try {
                // Here we would normally hit /api/messages
                // For now, simulate network delay
                await new Promise(r => setTimeout(r, 600));

                /* 
                // Actual integration when backend is ready:
                const res = await fetch('/api/messages', {
                    method: 'POST',
                    body: JSON.stringify({
                        receiverId: replyInfo.senderId,
                        content: message.trim()
                    })
                });
                if(!res.ok) throw new Error();
                */
                resolve();
            } catch (err) {
                reject(err);
            }
        });

        promiseToast(sendPromise, {
            loading: { title: 'Enviando respuesta...' },
            success: { title: 'Mensaje enviado ✅' },
            error: { title: 'Fallo al enviar el mensaje ❌' }
        });

        setIsSending(false);
        setIsOpen(false);
    };

    return (
        <AnimatePresence>
            {isOpen && (
                <div className="fixed inset-0 z-[99999] flex items-center justify-center pointer-events-none px-4">
                    {/* Dark overlay specifically for the modal area, keeps it fully focused */}
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        className="absolute inset-0 bg-black/40 backdrop-blur-sm pointer-events-auto"
                        onClick={() => setIsOpen(false)}
                    />

                    <motion.div
                        initial={{ opacity: 0, scale: 0.95, y: 10 }}
                        animate={{ opacity: 1, scale: 1, y: 0 }}
                        exit={{ opacity: 0, scale: 0.95, y: 10 }}
                        transition={{ type: 'spring', damping: 25, stiffness: 300 }}
                        className="relative w-full max-w-sm pointer-events-auto bg-[rgba(15,15,15,0.95)] backdrop-blur-2xl border border-white/10 rounded-3xl shadow-2xl overflow-hidden"
                    >
                        {/* Header */}
                        <div className="px-5 py-4 border-b border-white/5 bg-white/[0.02]">
                            <div className="flex items-center gap-3">
                                <div className="w-8 h-8 rounded-full bg-blue-500/20 border border-blue-500/30 flex items-center justify-center">
                                    <span className="text-xl">💬</span>
                                </div>
                                <div>
                                    <p className="text-xs font-mono font-black uppercase text-zinc-500 tracking-widest">Respondiendo a</p>
                                    <p className="text-sm font-bold text-white leading-tight">
                                        {replyInfo?.senderName || 'Usuario'}
                                    </p>
                                </div>
                            </div>
                            <div className="mt-3 p-3 rounded-xl bg-black/40 border border-white/5">
                                <p className="text-xs font-mono text-zinc-400 italic">
                                    "{replyInfo?.messageText || '...'}"
                                </p>
                            </div>
                        </div>

                        {/* Input Area */}
                        <form onSubmit={handleSend} className="p-2">
                            <div className="relative">
                                <input
                                    ref={inputRef}
                                    type="text"
                                    value={message}
                                    onChange={(e) => setMessage(e.target.value)}
                                    placeholder="Escribe tu mensaje..."
                                    className="w-full bg-transparent border-0 text-sm text-white placeholder:text-zinc-600 focus:ring-0 px-4 py-3 font-mono"
                                    disabled={isSending}
                                />
                                <button
                                    type="submit"
                                    disabled={!message.trim() || isSending}
                                    className="absolute right-2 top-1/2 -translate-y-1/2 p-2 bg-blue-500 hover:bg-blue-400 disabled:bg-zinc-800 disabled:text-zinc-600 text-black rounded-xl transition-all font-black text-[10px] uppercase tracking-widest"
                                >
                                    Enviar
                                </button>
                            </div>
                        </form>
                    </motion.div>
                </div>
            )}
        </AnimatePresence>
    );
}
